import { Inter } from "next/font/google";
import "./globals.css";
import { getDocuments } from "./lib/doc.js";
import Header from "./components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const allDocument = getDocuments();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div class="h-full lg:ml-72 xl:ml-80">
          <Header docs={allDocument} />
          <div class="relative px-4 pt-14 sm:px-6 lg:px-8">
            <main class="flex-auto py-12">
              {/* <!-- Green Top Overlay --> */}
              <div class="absolute inset-0 -z-10 mx-0 max-w-none overflow-hidden">
                <div class="absolute left-1/2 top-0 ml-[-38rem] h-[25rem] w-[81.25rem] dark:[mask-image:linear-gradient(white,transparent)]">
                  <div class="absolute inset-0 bg-gradient-to-r from-[#67b32c] to-[#DBFF75] opacity-40 [mask-image:radial-gradient(farthest-side_at_top,white,transparent)] dark:from-[#36b49f]/30 dark:to-[#DBFF75]/30 dark:opacity-100"></div>
                </div>
              </div>
              {/* <!-- Green Top Overlay End--> */}

              <article class="">
                <div class="relative">
                  <div class=" relative mx-auto px-4 ">
                    <div class="mx-auto grid max-w-[40rem] grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-5">
                      <div class="flex flex-col lg:pb-6 lg:col-span-2 justify-center">
                        <h1 class="mt-4 text-6xl font-extrabold leading-none tracking-tight text-slate-900 sm:text-5xl sm:leading-[3.5rem]">
                          Protocol
                        </h1>

                        <p class="mt-6 text-base leading-7 text-slate-700">
                          It doesn't matter if you have an API if nobody knows
                          how to use it. Teach people the ins and outs of OAuth
                          2.0 and JWTs in style with Protocol, a beautiful API
                          documentation template.
                        </p>

                        <div class="mt-10 flex flex-wrap gap-4">
                          <a
                            href="#"
                            class="inline-flex justify-center rounded-lg bg-slate-900 px-4 py-3 text-sm font-semibold text-white hover:bg-slate-700"
                            target="_blank"
                          >
                            <span>Get Started</span>
                          </a>
                        </div>
                      </div>
                      <div class="relative lg:col-span-3">
                        <img
                          src="./assets/banner.png"
                          width="1600"
                          height="1280"
                          class="relative z-20 -mb-36 aspect-[853/682] max-w-[630px] rounded-xl bg-slate-200 shadow-xl shadow-black/5 ring-1 ring-slate-900/5 sm:-mb-16 lg:-mb-8 xl:-mb-16"
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </article>
            </main>

            <footer class="mx-auto max-w-2xl space-y-10 pb-16 lg:max-w-5xl">
              <div class="relative h-8"></div>
              <div class="flex flex-col items-center justify-between gap-5 border-t border-zinc-900/5 pt-8 dark:border-white/5 sm:flex-row">
                <p class="text-xs text-zinc-600 dark:text-zinc-400">
                  © Copyright 2023. All rights reserved.
                </p>
              </div>
            </footer>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
